const routes = {
    login: '/',
    signup: '/signup',

    //Admin
    danhmuc: '/admin/danhmuc',
    home: '/admin/home',
    profile: '/:nickname',
    upload: '/upload',
    search: '/search',
    theloai: '/admin/theloai',
    sach: '/admin/sach',
    import: '/admin/importfile',
    nguoidung: '/admin/nguoidung',
    nguoidungdangky: '/admin/nguoidungdangky',
    chitietNDDK: '/admin/chitietNDDK/:id',
    phieumuon: '/admin/phieumuon',
    phieutra: '/admin/phieutra',
    phieumuononline: '/admin/phieumuononline',
    phieutraonline: '/admin/phieutraonline',
    phieudongphat: '/admin/phieudongphat',
    quanlypdp: '/admin/phieudongphat/quanly',
    NXB: '/admin/NXB',
    loaisach: '/admin/loaisach',
    tacgia: '/admin/tacgia',
    datra: '/admin/datra',
    nhapkhosach: '/admin/nhapkhosach',
    thongke: '/admin/thongke',
    //User
    userhome: '/userhome',
    chitietsach: '/chitietsach/:id',
    quanlyphieumuon: '/quanlyphieumuon',
    quanlyphieumuononline: '/quanlyphieumuononline',
    quanlyphieutra: '/quanlyphieutra',
    formphieumuon: '/chitietsach/formphieumuon/:id',
    chitietphieutra: '/chitietphieutra/:id',
    quanlypdp_user: '/quanlyphieudongphat',
    thongtintaikhoan: '/thongtintaikhoan',
    giosach: '/giosach',
    chitietphieumuonOnline: "/chi_tiet_phieu_muon_online",
    vnpay: "/vnpay",
    vnpay_su: "/VnpayForSignUp"
}
export default routes;